### ISSUE TITLE
Add helpful information to the SETUP.md

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xr#3]
The contents of the SETUP.md file gets included in
the README.md that gets delivered when a user runs the `exercism fetch`
command from their terminal.

At the very minimum, it should contain a link to the relevant
language-specific documentation on
[help.exercism.io](http://help.exercism.io).

It would also be useful to explain in a generic way how to run the tests.
Remember that this file will be included with _all_ the problems, so it gets
confusing if we refer to specific problems or files.

Some languages have very particular needs in terms of the solution: nested
directories, specific files, etc. If this is the case here, then it would be
useful to explain what is expected.

------

Thanks, @tejasbubane for suggesting that we add this documentation everywhere.
See [exercism.io#2198](https://github.com/exercism/exercism.io/issues/2198).

**Comment by rebelwarrior** [comment]
The setup for R doesn't work. There is no run_tests utilities.

**Comment by kytrinyx** [comment]
@jonboiser would you have time to look at this?

**Comment by rebelwarrior** [comment]
I did some digging and the issue is that run_utilities is a separate file that's included with hello world but not word-count. This seems like a complicated setup. And the information on how to set it up is on the hello world readme. That information (with more detail) should reside in the setup file.

**Comment by rebelwarrior** [comment]
I found the error and submitted a pull request. It was on TEST.md. There was a reference to "run_tests" that seems to be a different way of running the tests. The way it should say is `Rscript <testfile>`

**Comment by jonboiser** [comment]
@rebelwarrior Thanks for pointing this out. I forgot to update TEST.md when I was simplifying the problem folders to just have a few files.

I updated the TEST.md with the updated info and did a scan through all the docs to see if there was any more contradicting info.
