### ISSUE TITLE
docs/SETUP.md: should be moved to exercises/TRACK_HINTS.md

### ISSUE THREAD

**Issue by petertseng** [exercism/xr#33]
For the purpose of #10, `SETUP.md` in the root of this repo was moved to `docs/SETUP.md`.

Exercism does not assign special meaning to `docs/SETUP.md` (it **will not** be shown anywhere on http://exercism.io/languages/r) but it does assign special meaning to `SETUP.md` - it gets included in the README for each problem delivered to the student.

In addition, because of https://github.com/exercism/exercism.io/issues/3240, `SETUP.md` should get moved to `exercises/TRACK_HINTS.md`.

So, the two steps

1. allowing the instructions to be shown to the student again (`docs/SETUP.md` -> `SETUP.md`)
2. moving to the new location (`SETUP.md` -> `exercises/TRACK_HINTS.md`)

the file should be moved to `exercises/TRACK_HINTS.md`

**Comment by jonmcalder** [comment]
Thanks!
