### ISSUE TITLE
library() instead of require()

### ISSUE THREAD

**Issue by RMHogervorst** [exercism/xr#35]
Hi I noticed that `require` is used in scripts. This is not the recommended way to load a package. [1] 
I propose to change that to `library`

[1]: https://yihui.name/en/2014/07/library-vs-require/

**Comment by jonmcalder** [comment]
This is a good point. I have been perpetuating the use of `require` in the test scripts (by following the example set by the first few exercises) but it is better to use `library`. I'll make that change.

**Comment by RMHogervorst** [comment]
solved in #36
