### ISSUE TITLE
Create chat room on gitter

### ISSUE THREAD

**Issue by jonmcalder** [exercism/xr#38]
@kytrinyx @kotp I noticed there's no chat room for this repo on http://gitter.im and I figure it's probably worth creating one, especially as this track is being moved closer to launch.

**Comment by kotp** [comment]
@exercism/r member should be able to do so.

**Comment by jonmcalder** [comment]
In light of the discussions in [exercism/discussions/#43](https://github.com/exercism/discussions/issues/43) and [exercism/xcpp/#83](https://github.com/exercism/xcpp/issues/83), am opting to close this for now and revisit at a later stage.

In the meantime, have updated the README to link to exercism's support & dev rooms on gitter.
