### ISSUE TITLE
Installation docs suggest devtools which shouldn't be necessary

### ISSUE THREAD

**Issue by jonmcalder** [exercism/xr#44]
I was reviewing the installation doc and noticed that it suggests that installation of `devtools` and `Rtools` (for Windows) or `Xcode` (for Mac) might be necessary. These are fairly big dependencies which are usually only required if one needs to build R packages from source. The only strict package dependency I am aware of for this track is `testthat` which should be install-able directly from CRAN.

I might be overlooking something, but if these aren't strictly necessary then I don't think they should be mentioned since I can see how newer R users might run into problems while trying to install these much 'heavier' packages/software tools.

**Comment by morrme** [comment]
i agree.

**Comment by jonmcalder** [comment]
Thanks for weighing in here @morrme - I'll look at updating this.
